# Generated by Django 2.1.1 on 2018-10-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_auto_20181013_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomdetails',
            options={'verbose_name_plural': 'Room Details'},
        ),
    ]
