# Generated by Django 2.1.1 on 2018-09-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailField', models.CharField(max_length=30)),
                ('nameField', models.CharField(max_length=20)),
                ('passwordField', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='regnum',
            name='userNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.User'),
        ),
    ]
