# Generated by Django 2.1.1 on 2018-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletDis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletTak', models.CharField(max_length=420)),
            ],
        ),
    ]
