# Generated by Django 2.1.1 on 2018-09-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_deletdis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deletDis',
        ),
    ]
