# Generated by Django 2.1.1 on 2018-10-09 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_delete_deletdis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nameField',
            new_name='firstNameField',
        ),
        migrations.AddField(
            model_name='user',
            name='lastNameField',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
