# Generated by Django 2.1.1 on 2018-10-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_auto_20181009_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastNameField',
        ),
    ]
