# Generated by Django 2.1.1 on 2018-10-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0005_remove_user_lastnamefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastNameField',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
