# Generated by Django 2.1.1 on 2018-10-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0006_user_lastnamefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regnum',
            name='userNum',
        ),
        migrations.DeleteModel(
            name='RegNum',
        ),
    ]
