# Generated by Django 2.1.1 on 2018-10-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0007_auto_20181009_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
