# Generated by Django 2.1.1 on 2018-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LandingPage', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailField', models.CharField(max_length=30)),
                ('passwordField', models.CharField(max_length=20)),
                ('firstNameField', models.CharField(max_length=20)),
                ('lastNameField', models.CharField(max_length=20)),
            ],
        ),
    ]
