# Generated by Django 2.1.1 on 2018-10-21 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0002_auto_20181020_1650'),
        ('Room', '0002_auto_20181013_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('endDate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('emailID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.User', to_field='emailField')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.Room', to_field='roomID')),
            ],
        ),
    ]
