# Generated by Django 2.1.1 on 2018-11-20 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Room', '0003_auto_20181025_1617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('emailID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.Room', to_field='roomID')),
            ],
        ),
    ]
