# Generated by Django 2.1.1 on 2018-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20181113_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
