# Generated by Django 2.1.1 on 2018-11-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_booking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='bookingID',
        ),
    ]
