# Generated by Django 2.1.1 on 2018-11-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_auto_20181116_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.SlugField(blank=True, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
