# Generated by Django 2.1.1 on 2018-11-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_auto_20181116_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.CharField(blank=True, default='000000', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
