# Generated by Django 2.1.1 on 2018-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_auto_20181118_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
