# Generated by Django 2.1.1 on 2018-10-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0002_auto_20181011_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campus'},
        ),
    ]
