# Generated by Django 2.1.1 on 2018-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0003_auto_20181011_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campusName',
            field=models.CharField(max_length=30),
        ),
    ]
