# Generated by Django 2.1.1 on 2018-10-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0005_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='campus',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
