# Generated by Django 2.1.1 on 2018-10-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailField',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
